import React from 'react';
import { FileText, Activity, DollarSign, Building2, CheckCircle2 } from 'lucide-react';
import { InsuranceAnalysis } from '../types';

interface ResultsDisplayProps {
  analysis: InsuranceAnalysis;
}

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ analysis }) => {
  return (
    <div className="space-y-8 animate-fade-in-up">
      {/* Summary Card */}
      <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
        <div className="bg-slate-50 px-6 py-4 border-b border-slate-200 flex items-center gap-3">
          <Building2 className="text-blue-600" size={20} />
          <h2 className="text-lg font-semibold text-slate-900">
            {analysis.companyName || "Identified Insurance Provider"}
          </h2>
        </div>
        <div className="p-6">
          <p className="text-slate-700 leading-relaxed">
            {analysis.summary}
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {/* Coverage Section */}
        <div className="md:col-span-1">
          <div className="bg-blue-50 rounded-xl p-6 h-full border border-blue-100 relative overflow-hidden group hover:shadow-md transition-all">
            <div className="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 bg-blue-100 rounded-full opacity-50 blur-2xl group-hover:bg-blue-200 transition-colors"></div>
            <div className="relative z-10">
              <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center shadow-sm text-blue-600 mb-4">
                <CheckCircle2 size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-900 mb-2">Coverage</h3>
              <p className="text-sm text-slate-500 mb-4 uppercase tracking-wider font-semibold">What is covered</p>
              <div className="prose prose-sm prose-blue text-slate-700">
                <div dangerouslySetInnerHTML={{ __html: analysis.coverage.replace(/\n/g, '<br/>') }} />
              </div>
            </div>
          </div>
        </div>

        {/* Action Plan Section */}
        <div className="md:col-span-1">
          <div className="bg-emerald-50 rounded-xl p-6 h-full border border-emerald-100 relative overflow-hidden group hover:shadow-md transition-all">
            <div className="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 bg-emerald-100 rounded-full opacity-50 blur-2xl group-hover:bg-emerald-200 transition-colors"></div>
            <div className="relative z-10">
              <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center shadow-sm text-emerald-600 mb-4">
                <Activity size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-900 mb-2">If You're Sick</h3>
              <p className="text-sm text-slate-500 mb-4 uppercase tracking-wider font-semibold">Action Plan</p>
              <div className="prose prose-sm prose-emerald text-slate-700">
                <div dangerouslySetInnerHTML={{ __html: analysis.actionSteps.replace(/\n/g, '<br/>') }} />
              </div>
            </div>
          </div>
        </div>

        {/* Reimbursement Section */}
        <div className="md:col-span-1">
           <div className="bg-purple-50 rounded-xl p-6 h-full border border-purple-100 relative overflow-hidden group hover:shadow-md transition-all">
            <div className="absolute top-0 right-0 -mt-4 -mr-4 w-24 h-24 bg-purple-100 rounded-full opacity-50 blur-2xl group-hover:bg-purple-200 transition-colors"></div>
            <div className="relative z-10">
              <div className="w-10 h-10 bg-white rounded-lg flex items-center justify-center shadow-sm text-purple-600 mb-4">
                <DollarSign size={20} />
              </div>
              <h3 className="text-lg font-bold text-slate-900 mb-2">Reimbursement</h3>
              <p className="text-sm text-slate-500 mb-4 uppercase tracking-wider font-semibold">Financials</p>
              <div className="prose prose-sm prose-purple text-slate-700">
                <div dangerouslySetInnerHTML={{ __html: analysis.reimbursement.replace(/\n/g, '<br/>') }} />
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="bg-amber-50 border border-amber-100 rounded-lg p-4 flex items-start gap-3">
        <FileText className="text-amber-600 flex-shrink-0 mt-0.5" size={18} />
        <div>
          <h4 className="text-sm font-semibold text-amber-800">Disclaimer</h4>
          <p className="text-xs text-amber-700 mt-1">
            This analysis is generated by AI and may not capture every detail of your specific policy. 
            Always refer to the original document or contact your insurance provider for official confirmation of coverage.
          </p>
        </div>
      </div>
    </div>
  );
};

export default ResultsDisplay;
